package com.sinorail.cwzywst.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicUser<M extends BaseDicUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setUserCode(java.lang.String userCode) {
		set("USER_CODE", userCode);
	}

	public java.lang.String getUserCode() {
		return get("USER_CODE");
	}

	public void setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
	}

	public java.lang.String getUserName() {
		return get("USER_NAME");
	}

	public void setPasswd(java.lang.String passwd) {
		set("PASSWD", passwd);
	}

	public java.lang.String getPasswd() {
		return get("PASSWD");
	}

	public void setOfficeId(java.lang.String officeId) {
		set("OFFICE_ID", officeId);
	}

	public java.lang.String getOfficeId() {
		return get("OFFICE_ID");
	}

	public void setOfficeName(java.lang.String officeName) {
		set("OFFICE_NAME", officeName);
	}

	public java.lang.String getOfficeName() {
		return get("OFFICE_NAME");
	}

	public void setUnitId(java.lang.String unitId) {
		set("UNIT_ID", unitId);
	}

	public java.lang.String getUnitId() {
		return get("UNIT_ID");
	}

	public void setUnitName(java.lang.String unitName) {
		set("UNIT_NAME", unitName);
	}

	public java.lang.String getUnitName() {
		return get("UNIT_NAME");
	}

	public void setRoleId(java.lang.String roleId) {
		set("ROLE_ID", roleId);
	}

	public java.lang.String getRoleId() {
		return get("ROLE_ID");
	}

	public void setRoleName(java.lang.String roleName) {
		set("ROLE_NAME", roleName);
	}

	public java.lang.String getRoleName() {
		return get("ROLE_NAME");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public void setField1(java.math.BigDecimal field1) {
		set("FIELD1", field1);
	}

	public java.math.BigDecimal getField1() {
		return get("FIELD1");
	}

	public void setField2(java.lang.String field2) {
		set("FIELD2", field2);
	}

	public java.lang.String getField2() {
		return get("FIELD2");
	}

	public void setEntryTime(java.util.Date entryTime) {
		set("ENTRY_TIME", entryTime);
	}

	public java.util.Date getEntryTime() {
		return get("ENTRY_TIME");
	}

	public void setCreaterId(java.lang.String createrId) {
		set("CREATER_ID", createrId);
	}

	public java.lang.String getCreaterId() {
		return get("CREATER_ID");
	}

	public void setParentId(java.lang.String parentId) {
		set("PARENT_ID", parentId);
	}

	public java.lang.String getParentId() {
		return get("PARENT_ID");
	}

}
