package com.sinorail.cwzywst.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDicPopedom<M extends BaseDicPopedom<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}

	public java.lang.String getId() {
		return get("ID");
	}

	public void setPopedomName(java.lang.String popedomName) {
		set("POPEDOM_NAME", popedomName);
	}

	public java.lang.String getPopedomName() {
		return get("POPEDOM_NAME");
	}

	public void setForwardAction(java.lang.String forwardAction) {
		set("FORWARD_ACTION", forwardAction);
	}

	public java.lang.String getForwardAction() {
		return get("FORWARD_ACTION");
	}

	public void setPopedomType(java.lang.String popedomType) {
		set("POPEDOM_TYPE", popedomType);
	}

	public java.lang.String getPopedomType() {
		return get("POPEDOM_TYPE");
	}

	public void setXh(java.math.BigDecimal xh) {
		set("XH", xh);
	}

	public java.math.BigDecimal getXh() {
		return get("XH");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}

	public java.lang.String getRemark() {
		return get("REMARK");
	}

	public void setField1(java.math.BigDecimal field1) {
		set("FIELD1", field1);
	}

	public java.math.BigDecimal getField1() {
		return get("FIELD1");
	}

	public void setField2(java.lang.String field2) {
		set("FIELD2", field2);
	}

	public java.lang.String getField2() {
		return get("FIELD2");
	}

	public void setParentId(java.lang.String parentId) {
		set("PARENT_ID", parentId);
	}

	public java.lang.String getParentId() {
		return get("PARENT_ID");
	}

	public void setTarget(java.lang.String target) {
		set("TARGET", target);
	}

	public java.lang.String getTarget() {
		return get("TARGET");
	}

	public void setNavIcon(java.lang.String navIcon) {
		set("NAV_ICON", navIcon);
	}

	public java.lang.String getNavIcon() {
		return get("NAV_ICON");
	}

	public void setNavIconWidth(java.lang.String navIconWidth) {
		set("NAV_ICON_WIDTH", navIconWidth);
	}

	public java.lang.String getNavIconWidth() {
		return get("NAV_ICON_WIDTH");
	}

	public void setNavIconHeight(java.lang.String navIconHeight) {
		set("NAV_ICON_HEIGHT", navIconHeight);
	}

	public java.lang.String getNavIconHeight() {
		return get("NAV_ICON_HEIGHT");
	}

	public void setIsMenu(java.math.BigDecimal isMenu) {
		set("IS_MENU", isMenu);
	}

	public java.math.BigDecimal getIsMenu() {
		return get("IS_MENU");
	}

}
