package com.sinorail.cwzywst.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("DIC_POPEDOM", "ID", DicPopedom.class);
		arp.addMapping("DIC_ROLE", "ID", DicRole.class);
		arp.addMapping("DIC_ROLE_POPEDOM", "ID", DicRolePopedom.class);
		arp.addMapping("DIC_USER", "ID", DicUser.class);
	}
}

