package com.sinorail.cwzywst.model;

import java.util.List;

import com.jfinal.plugin.activerecord.SqlPara;
import com.sinorail.cwzywst.model.base.BaseDicPopedom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicPopedom extends BaseDicPopedom<DicPopedom> {
	
	public static final DicPopedom dao = new DicPopedom().dao();
	
	public List<DicPopedom> list(DicPopedom popedom) {
		SqlPara sqlp = getSqlPara("popedom.paginateSelect", popedom);
		return find(sqlp);
	}

	public List<DicPopedom> menuList() {
		return find(getSql("popedom.menuList"));
	}
	
	public List<DicPopedom> menuListByRoleId(DicUser dicUser) {
		return find(getSql("popedom.menuListByRoleId"), dicUser.getRoleId());
	}
	
	/**
	 * 权限分配列表(root)
	 */
	public List<DicPopedom> matchList(String roleId) {
		return find(getSql("popedom.matchList"), roleId);
	}
	/**
	 * 权限分配列表(普通)
	 */
	public List<DicPopedom> matchListBySessionRoleId(String sessionRoleId ,String roleId) {
		return find(getSql("popedom.matchListBySessionRoleId"), sessionRoleId, roleId);
	}

	/**
	 * 用于登录验证
	 * @param roleId
	 * @return
	 */
	public List<DicPopedom> queryByRoleId(String roleId) {
		return find(getSql("popedom.queryByRoleId"), roleId);
	}

}
