package com.sinorail.cwzywst.model;

import com.sinorail.cwzywst.model.base.BaseDicRolePopedom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicRolePopedom extends BaseDicRolePopedom<DicRolePopedom> {
	public static final DicRolePopedom dao = new DicRolePopedom().dao();
}
